### ISSUE TITLE
Converting ACD files to L5X?

### ISSUE THREAD

**Issue by mutigozel** [tnunnink/L5Sharp#10]
Can I use this library to convert ACD files to L5X?

**Comment by tnunnink** [comment]
Unfortunately, no. This library is just an API wrapper over the L5X schema. It requires that you first have the L5X.

It would be nice if Rockwell provided a way to do that programmatically, but I have not found anything on it.

**Comment by tnunnink** [comment]
This is now possible with the L5Sharp.Logix extension library. You can add this project from NuGet. It will use the native Logix SDK to open and save the file as an L5X and then load the contents of the file, returning an instance of L5X. This of course requires that you have the SDK installed and licensed locally.

**Comment by mutigozel** [comment]
Cool. Can you provide a simple example code?

**Comment by tnunnink** [comment]
```csharp
var content = ACD.LoadAsync("\pathtofile\project.ACD");
```
