### ISSUE TITLE
Proposal to Extend L5Sharp Support to .NET Standard 2.0

### ISSUE THREAD

**Issue by ivanbenko** [tnunnink/L5Sharp#13]
First, I'd like to express my gratitude for L5Sharp—it's been an invaluable discovery for me.

I believe we can broaden the appeal of L5Sharp by extending support to include the .NET Framework by targeting .Net Standard 2.0 as well. This change would significantly benefit users with legacy applications, like myself, who are currently limited to forking the project for compatibility.

I've successfully adapted the code for .NET Framework 4.8 in my testing and am willing to prepare and submit a pull request. I think this enhancement could make the project more accessible to a wider audience.

Looking forward to hearing your thoughts on this suggestion.

Thank you for considering my proposal.

**Comment by tnunnink** [comment]
.NET Standard 2.0 support has been added and released in the latest version [2.0.0](https://www.nuget.org/packages/L5Sharp/2.0.0)
