### ISSUE TITLE
Can't Derive from Sealed Type

### ISSUE THREAD

**Issue by jojoguy10** [tnunnink/L5Sharp#23]
Did you end up sealing the base classes in v2.2.0?  This worked before, but now it's saying it's sealed.  Is it possible to keep them unsealed?
![devenv_yiDzORCrWp](https://github.com/tnunnink/L5Sharp/assets/7492427/640867a3-efc0-4347-9f6d-e7440de4df6b)

**Comment by tnunnink** [comment]
I did. I was trying to suppress some compiler warnings due to setting virtual member (Name) in derived class constructors. I just removed the sealed modifier and changed how I set the member to avoid those warnings. See version 2.2.1 for the update.
