### ISSUE TITLE
Instruction doesn't support branch syntax

### ISSUE THREAD

**Issue by billpeet** [tnunnink/L5Sharp#31]
Hey mate, just want to say this library is amazing! Going to be a huge help on my current project.

One thing I've noticed, branches in L5X seem to be represented with a comma-separated syntax, e.g.:
```xml
<Text>
<![CDATA[[XIC(Var1) ,XIC(Var2) ]OTE(Var3);]]>
</Text>
```
represents
```
|------[ Var1 ]---------------------[ Var3 ]--|
    |              | 
    ----[ Var2 ]---
```
Looks like it surrounds the block with [ ], with each branch comma-separated.
Doesn't look like Instruction.Parse supports this, it just picks up the first instruction (`XIC(Var1)`).

**Comment by tnunnink** [comment]
Hey there,

Yes instruction is meant to represent a single instruction of the rung. You are correct about the format, but you want the class NeutralText, which represents a sequence of instructions. NeutralText should have methods for parsing and getting the collection of instructions in it.

Glad you find the project useful!
